# Form implementation generated from reading ui file 'client_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 335)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chatBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.chatBox.setGeometry(QtCore.QRect(10, 10, 351, 241))
        self.chatBox.setObjectName("chatBox")
        self.input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input.setGeometry(QtCore.QRect(10, 270, 261, 20))
        self.input.setObjectName("input")
        self.btnSend = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(280, 270, 75, 23))
        self.btnSend.setObjectName("btnSend")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 374, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSend.setText(_translate("MainWindow", "Gửi"))
